FROM node:18.16.0-alpine as builder
WORKDIR /app

COPY ../../ ./
RUN npm i -g pnpm@8.8.0
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

RUN npx nx run web:build:prod
RUN pnpm deploy --filter=web --prod /apps/web

FROM nginx
EXPOSE 1111
COPY --from=builder /app/apps/web/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
