FROM node:18.16.0-alpine as builder
WORKDIR /app

COPY ../../ ./
RUN npm i -g pnpm@8.7.4 
RUN pnpm i
RUN npx nx run web:build

FROM nginx
EXPOSE 1111
COPY --from=builder /app/apps/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html