version: '1.25'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
