version: '3'
services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.prod
    ports:
      - '1111:1111'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
    ports:
      - '2222:2222'
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./apps/api/.env.prod
    environment:
      - NODE_ENV=production

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=tampham
      - POSTGRES_PASSWORD=05122001
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
