FROM node:18.16.0-alpine
WORKDIR /usr/app

COPY --chown=node:node package*.json ./
COPY . .
RUN npm i -g pnpm@8.7.4
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN npx nx run api:build:prod
RUN pnpm deploy --filter=api --prod /apps/api
ENV NODE_ENV=production




CMD ["/bin/sh", "-c", "npx nx run api:start:prod"]