export { ReactComponent as I18nIcon } from '../assets/icons/svg/i18n.svg';
export { ReactComponent as NoticationIcon } from '../assets/icons/svg/notication.svg';
export { ReactComponent as BillingIcon } from '../assets/icons/svg/builling.svg';
export { ReactComponent as IconDolar } from '../assets/icons/svg/dolar.svg';
export { ReactComponent as IconFAQ } from '../assets/icons/svg/faq.svg';
export { ReactComponent as IconHelp } from '../assets/icons/svg/help.svg';
export { ReactComponent as IconLogout } from '../assets/icons/svg/logout.svg';
export { ReactComponent as IconPerson } from '../assets/icons/svg/person.svg';
export { ReactComponent as IconSetting } from '../assets/icons/svg/setting.svg';
export { ReactComponent as IconHome } from '../assets/icons/svg/home.svg';
export { ReactComponent as IconDashBoard } from '../assets/icons/svg/dashboard.svg';
export { ReactComponent as IconArrowDown } from '../assets/icons/svg/arrow_down.svg';
export { ReactComponent as IconDeleteAction } from '../assets/icons/svg/delete-action.svg';
export { ReactComponent as IconEditAction } from '../assets/icons/svg/edit-action.svg';
export { ReactComponent as IconUser } from '../assets/icons/svg/user.svg';
export { ReactComponent as IconEye } from '../assets/icons/svg/eye.svg';

export { ReactComponent as IconEyeClose } from '../assets/icons/svg/eye-close.svg';
export { ReactComponent as IconBook } from '../assets/icons/svg/book.svg';
export { ReactComponent as IconClasses } from '../assets/icons/svg/classes.svg';
export { ReactComponent as IconPencil } from '../assets/icons/svg/pencil.svg';
export { ReactComponent as IconSchool } from '../assets/icons/svg/school.svg';
export { ReactComponent as IconClassesName } from '../assets/icons/svg/classes-new.svg';
export { ReactComponent as IconContacs } from '../assets/icons/svg/contacts.svg';
export { ReactComponent as IconNews } from '../assets/icons/svg/news.svg';
export { ReactComponent as IconAssessment } from '../assets/icons/svg/assessment.svg';
export { ReactComponent as NoDataSvg } from '../assets/icons/svg/no-data.svg';
export { ReactComponent as PaymentIcon } from '../assets/icons/svg/payment.svg';
export { ReactComponent as CheckoutSvg } from '../assets/icons/svg/Self-checkout.svg';

export { IconSearch } from './SearchIcon';
export { ChatIcon } from './ChatIcon';
// export { IconSearch } from './SearchIcon';
