export enum RoleEnum {
  'WEB_ADMIN' = 1,
  'WEB_STAFF' = 2,
  'CENTER_ADMIN' = 3,
  'CENTER_TUTOR' = 4,
  'PESONAL_TUTOR' = 5,
  'STUDENT' = 6,
  'PARENT' = 7,
  'ANONYMOUS' = 8,
}
export enum RolesEnumName {
  WEB_ADMIN = 'WEB_ADMIN',
  WEB_STAFF = 'WEB_STAFF',

  CENTER_ADMIN = 'CENTER_ADMIN',
  CENTER_TUTOR = 'CENTER_TUTOR',

  PESONAL_TUTOR = 'PESONAL_TUTOR',

  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  ANONYMOUS = 'ANONYMOUS',
}
