FROM node:18.16.0-alpine
WORKDIR /app
COPY ../../package.json .

COPY ../../ ./
RUN npm i -g pnpm@8.7.4 
RUN pnpm i
ENV NODE_ENV=production
RUN npx nx run api:build:prod

CMD ["npx", "nx", "run", "api:start:prod"]
