FROM node:20.0.0
WORKDIR /usr/app

COPY ../../ ./

RUN npm i -g pnpm@8.7.4
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN npx nx run api:build:prod
RUN pnpm deploy --filter=api --prod /apps/api
ENV NODE_ENV=production

CMD ["/bin/sh", "-c", "npx nx run api:start:prod"]