on:
  pull_request:
  push:
    branches: [deloy]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Test
      #   run: |
      #     npm install
      #     npm run test

      - name: Action/Render_Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        # Only run this step if the branch is deloy
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
