on:
  pull_request:
  push:
    branches: [deloy]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Test
      #   run: |
      #     npm install
      #     npm run test

      - name: Action/Render_Deploy
        # Only run this step if the branch is deloy
        if: github.ref == 'refs/heads/deloy'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
