name: Build Web & Deploy

on:
  push:
    branches: [prod-web]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy web to google Cloud
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/pttam512/org-doan
            git checkout prod-web
            git pull
            docker-compose sudo docker compose up -d web --build
